name: Update Blog Metadata

on:
  push:
    branches: [ "main" ]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Workload Identity Federation
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.project_id }}
        workload_identity_provider: ${{ secrets.workload_identity_provider }}
        service_account: ${{ secrets.service_account }}

    - name: Google Cloud Login
      run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
    
    - name: Go Test
      run: go test -v ./...

    - name: Update Metadata
      run: ./build.sh

